name: Select QA Environment
description: Select an available QA environment
inputs:
  Table:
    description: Name of the Google Firestore Collection to query for environment details.
    required: true
    default: qa-envs
outputs:
  url:
    description: The URL of the QA environment
runs:
  using: node16
  main: dist/index.js
branding:
  icon: server
  color: blue
